apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-web.fullname" . }}
  labels:
    {{- include "simple-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - nodePort: {{ .Values.service.nodePort }}
      targetPort: http
      port: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "simple-web.selectorLabels" . | nindent 4 }}
